import type {StudioRuntimeState} from './state';

const browserRuntimeKeys = [
  'connectionGroups',
  'connections',
  'schemaOverview',
  'kvOverview',
  'selectedObjectName',
  'browserNavMode',
  'selectedTreeKeys',
  'expandedTreeKeys',
  'databaseListCache',
  'activeDatabaseMap',
  'databaseVectorizeStatusMap',
  'currentObjectType',
  'objectViewMode',
  'vectorizeOverviewModalOpen',
  'vectorizeOverviewLoading',
  'vectorizeOverviewData',
  'browserDetailCollapsed',
  'tableDetail',
  'tableDetailLoading',
  'kvObjectDetail',
  'kvObjectDetailLoading',
  'redisHierarchyPath',
  'redisBrowserRows',
  'redisBrowserLoading',
  'redisExpandedRowKeys',
  'redisSelectedRowKey',
  'redisKeyModalOpen',
  'redisKeyModalSubmitting',
  'redisKeyModalMode',
  'redisKeyForm',
  'prepareConnectionTreeData',
  'loadDatabaseListForConnection',
  'refreshVectorizeStatusForConnection',
  'refreshAllVectorizeStatuses',
  'pruneVectorizeStatusMap',
  'startVectorizeStatusPolling',
  'stopVectorizeStatusPolling',
  'loadConnections',
  'refreshConnections',
  'openCreateGroupModal',
  'openRenameGroupModal',
  'closeGroupModal',
  'confirmGroupModal',
  'removeConnectionGroup',
  'saveConnection',
  'previewConnectionDatabases',
  'testConnection',
  'disconnectConnection',
  'removeConnection',
  'syncSchema',
  'loadOverview',
  'clearTableStatsPollingTimer',
  'clearAllTableStatsPollingTimers',
  'applyTableStatsSnapshot',
  'isDatabaseNodeExpanded',
  'collectExpandedDatabaseTargets',
  'fetchTableStatsForDatabase',
  'scheduleTableStatsForExpandedDatabases',
  'loadObjectNames',
  'refreshCurrentObjects',
  'refreshCurrentPageObjects',
  'loadCategoryObjects',
  'loadTreeChildrenByKey',
  'handleTreeSelect',
  'handleTreeExpand',
  'handleConnectionTreeDrop',
  'handleTreeRightClick',
  'closeContextMenu',
  'loadSavedQueries',
  'openVectorizeOverview',
  'enqueueDatabaseRevectorize',
  'vectorizeSingleTable',
  'interruptDatabaseVectorize',
  'selectObject',
  'loadObjectDetail',
  'clearObjectDetail',
  'openCreateRedisKeyModal',
  'openEditRedisKeyModal',
  'closeRedisKeyModal',
  'confirmRedisKeyModal',
  'deleteRedisKey',
  'handleRedisBrowserExpand',
  'toggleRedisBrowserPath',
  'loadMoreRedisBrowserRows',
  'handleRedisHierarchySelect',
  'openQueryTabByObject',
  'openSaveQueryModal',
  'saveCurrentQuery',
  'openSavedQueryTab',
  'openSavedQueryTabByTitle',
  'expandConnectionNode',
  'ensureConnectionTreeExpanded',
  'buildDatabaseRootNodeKey',
  'buildDatabaseNodeKey',
  'buildCategoryNodeKey',
  'buildObjectNodeKey',
  'expandCategoryNode',
] as const;

type BrowserRuntimeKey = typeof browserRuntimeKeys[number];

export function createStudioBrowserRuntime<T extends StudioRuntimeState>(state: T) {
  const runtime = {} as Pick<T, Extract<BrowserRuntimeKey, keyof T>>;
  browserRuntimeKeys.forEach((key) => {
    if (key in state) {
      (runtime as Record<string, unknown>)[key] = state[key];
    }
  });
  return runtime;
}
